###############################################################
# Program:
#     project04, Makefiles
#     Brother Schwieder, CS124
# Author:
#     Jamie Hurd
# Summary:
#     Classes for BudgetCT, controlling the
#location of objects in the budget calculator.
###############################################################
#atom may replace tabs with two spaces, which won't work for makefile
#must tab over the g++ lines(?)

# Insert your rule for a.out here:
a.out:	project04.cpp
	g++	-c	project04.cpp

# Insert your rule for robot.o here:
project04.o:	project04.cpp project04.hpp
	g++ -c project04.cpp
