###############################################################
# Program:
#     Assignment 16, Makefiles
#     Brother Schwieder, CS124
# Author:
#     Jamie Hurd
# Summary:
#     This program incorporates
# Estimated:
# Actual:
# The most difficult part comprised
###############################################################

a.out: lander.h lander.cpp

# Insert your rule for robot.o here:
lander.o: lander.cpp lander.hpp
	g++ -c lander.cpp

# Insert your rule for point.o here:
point.o: point.cpp point.hpp
	g++ -c point.cpp

	# Insert your rule for check06a.o here:
main.o: main.cpp
	g++ -c main.cpp
